app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/




/**
 * Route Route
 * 
 */
Route::get('/login', ['as'=> 'login', 'uses'=> 'AuthController@index']);
Route::post('/login', ['as'=> 'login', 'uses'=> 'AuthController@store']);


/**
 * Guests Route
 * untuk mengakses public page
 */
Route::get('/', 'HomeController@index');
Route::get('/watch', ['as'=> 'watch', 'uses'=> 'VideoController@watch']);


/**
 * Sample Route
 *
 */
Route::get('upload', ['as'=> 'upload', 'uses'=> 'UploadController@getUpload']);

//Route::post('upload', ['as'=> 'uploadvideo', 'uses'=> 'UploadController@postVideo']);
Route::get('uploadfile', 'UploadController@upload');
Route::post('uploadfile','UploadController@upload');


Route::post('video/informasi', ['as'=> 'video.informasi.add', 'uses'=> 'UploadController@addInformasi']);

/** 
 * Tv Route 
 */
Route::resource('tv', 'TvController');

/**
 * Category Routes
 * 
 */
Route::resource('categories', 'CategoryController');
Route::get('api/categories', array('as'=>'api.categories', 'uses'=>'CategoryController@getDatatable'));

/**
 * License Routes
 * 
 */
Route::resource('licenses', 'LicenseController');
Route::get('api/licenses', array('as'=>'api.licenses', 'uses'=>'LicenseController@getDatatable'));


//user access
Route::get('/me', array('before'=> 'auth', function(){
	return Sentry::getUser();
}));

Route::get('/logout', array('as'=>'logout', function(){
	Sentry::logout();
	return Redirect::to('/');
}));
//OAuth 
Route::get('oauth', function(){

	$provider = new League\OAuth2\Client\Provider\Xtwoend(array(
	    'clientId'  	=>  'ymyi8bGd6nSP0WhdmmLz9rUxAGSQ3pT6DlVDIau1',
	    'clientSecret'  =>  'JX3ymChnENBoYfuygyssta5FqZOAFeBKe9QRpvTg',
	    'redirectUri'   =>  'http://localhost/merahputih/public/oauth'
	));

	if ( ! isset($_GET['code'])) {

	    // If we don't have an authorization code then get one
	    header('Location: '.$provider->getAuthorizationUrl());
	    exit;

	} else {
		
	    // Try to get an access token (using the authorization code grant)
	    $token = $provider->getAccessToken('authorization_code', [
	        'code' => $_GET['code']
	    ]);
	    // Optional: Now you have a token you can look up a users profile data
	    try {
	        // We got an access token, let's now get the user's details
	        $userDetails = $provider->getUserDetails($token);

	        try
			{
			    // Find the user using the user email address
			    $user = Sentry::findUserByLogin($userDetails->email);
		
			    Sentry::loginAndRemember($user);
	        	
	        	return Redirect::to('me');
			    // Now you can send this code to your user via email for example.
			}
			catch (Cartalyst\Sentry\Users\UserNotFoundException $e)
			{
			   $user = Sentry::createUser(array(
			        'email'     => $userDetails->email,
			        'password'  => Str::random(40),
			        'first_name' => $userDetails->firstName,
			        'last_name'	=> $userDetails->lastName,
			        'activated' => true,
			    ));

			    // Find the group using the group id
			    $userGroup = Sentry::findGroupById(1);

			    // Assign the group to the user
			    $user->addGroup($userGroup);

			    Sentry::loginAndRemember($user);

	        	return Redirect::to('me');
			}

	        // Use these details to create a new profile
	        //printf('Hello %s!', $userDetails->firstName);

	    } catch (Exception $e) {
	        // Failed to get user details
	        exit($e->getMessage());
	    }
	}
});


//rotue tester
Route::get('/thumb', function(){
	$path = '/home/xtwoend/Video/hunterxhunter.mp4';
	$destination = '/home/xtwoend/Video/';
	$name = 'dadang.jpg';
	return Sonus::getThumbnails($path, $destination.$name, 5);
});

app/controllers/CategoryController.php
<?php

/**
 * Category Controller
 *
 * NOTICE OF LICENSE
 *
 * Licensed under the MIT License.
 *
 * This source file is subject to the MIT License that is
 * bundled with this package in the LICENSE file.  It is also available at
 * the following URL: http://opensource.org/licenses/MIT
 *
 * @package    controllers
 * @version    1.0.0
 * @author     Abdul Hafidz A <aditans88@gmail.com>
 * @license    MIT License
 */

class CategoryController extends \BaseController {

	/**
	 * construct 
	 *
	 * @return void
	 */
	public function __construct()
	{
		parent::__construct();
	}


	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{	
		return $this->theme->of('categories.index')->render();
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return $this->theme->of('categories.create')->render();
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{	
		$input = Input::all();
		$create = Category::create($input);
		return ($create)? Redirect::to('categories') : Redirect::back('error');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

	/**
	 * resource datatable
	 *
	 * @return json
	 */
	public function getDatatable()
	{	
		return Datatable::collection(Category::all())
        ->showColumns('id', 'category', 'slug')
        ->searchColumns('category')
        ->orderColumns('id','category')
        ->make();
    }	
}

app/views/categories/create.blade.php
<div id="highlighted" class="bg-color-grayLight1">
      <div class="container">
        <div class="row">
          <div class="highlighted-blog-single col-xs-12">
            <div class="fade-in text-center vertical-center">
              <h2 class="blog-single-title text-color-theme">{{ 'title' }}</h2>
            </div>
            <ul class="blog-post-info list-inline">
              <li>Alice Doe on 16 May</li>
              <li><a href="#">46.2K Plays / 711 Likes / 12 Comments</a></li>
              <li>1 Year ago</li>
            </ul>
          </div> <!-- /highlighted-image-blog -->

        </div> <!-- /row -->
      </div> <!-- /container -->      
</div> <!-- /highlighted -->

  <div id="blog-single" class="content">
      <div class="container">
        <div class="row">

          <div class="main-content col-xs-12 col-md-8 col-md-offset-2">
            <div class="region">
                  <br>
                  <div class="blog-single-post-content">
                     
                  </div> <!-- /blog-single-post-content -->

                  <div class="theme-comments">
                        
                    <h4 class="theme-comments-title">Category</h4>
                    
                    <form class="form-horizontal" method="post" role="form" action="{{ route('categories.store') }}">                  
                      
                      <div class="form-group">
                        <div class="col-xs-12">
                          <textarea class="form-control" rows="8" id="comment" name="category" placeholder="Comment"></textarea>
                        </div> <!-- /col-xs-12 -->
                      </div> <!-- /form-group -->
                      
                      <div class="form-group text-center">
                        <div class="col-xs-12">
                          <input type="submit" class="btn btn-primary btn-sm btn-block margin-top-20" id="submit" name="submit" value="submit comment" />
                        </div> <!-- /col-xs-12 -->
                      </div> <!-- /form-group -->
                    </form>
                    
                    <div class="theme-comment">
                      <div class="row">
                        <div class="theme-comment-picture col-sm-2 hidden-xs">
                          <img src="img/people/user1.jpg" class="img-responsive" alt="User 1" title="User 1" />
                        </div> <!-- /theme-comment-info -->
                        
                        <div class="theme-comment-message col-sm-10">
                          <h5 class="theme-comment-subject">Lorem Ipsum</h5>
                          <p class="theme-comment-info"><small>John Doe on Fri, 05/17/2014 - 10:19</small></p>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim felis, mollis a lacinia laoreet, rutrum at velit. Fusce quis neque nisl. Proin faucibus leo fermentum venenatis pharetra. Aenean placerat scelerisque justo, ac ultrices neque interdum eu. Praesent et lobortis nunc.</p>
                          <p>In ac vulputate nisi. Aliquam aliquam viverra magna id sollicitudin.</p>
                          <p><small><a href="#">reply</a></small></p>
                        </div> <!-- /theme-comment-message -->
                      </div> <!-- /row -->
                    </div> <!-- /theme-comment -->
                    
                    <div class="theme-comment">
                      <div class="row">
                        <div class="theme-comment-picture col-sm-2 hidden-xs">
                          <img src="img/people/user2.jpg" class="img-responsive" alt="User 2" title="User 2" />
                        </div> <!-- /theme-comment-info -->
                        
                        <div class="theme-comment-message col-sm-10">
                          <h5 class="theme-comment-subject">Proin aliquam</h5>
                          <p class="theme-comment-info"><small>Jane Doe on Thu, 05/16/2014 - 12:44</small></p>
                          <p>Fusce et pharetra massa. Proin aliquam eros porttitor nulla dictum sollicitudin. Suspendisse potenti. Etiam ac odio nec est cursus luctus et id turpis.</p>
                          <p>Duis varius nunc id semper tincidunt. Aenean sit amet velit eleifend, rhoncus metus a, feugiat enim. Sed vestibulum leo quis lectus semper, eget pulvinar ligula adipiscing.</p>
                          <p><small><a href="#">reply</a></small></p>
                        </div> <!-- /theme-comment-message -->
                      </div> <!-- /row -->
                    </div> <!-- /theme-comment -->

                  </div> <!-- /theme-comments -->

                </div> <!-- /blog-post -->
              </div> <!-- /blog-content-block -->

            </div> <!-- /region -->
          </div> <!-- /main-content -->

        </div> <!-- /row -->
      </div> <!-- /container -->
    </div> <!-- /content -->

app/views/categories/index.blade.php
<div id="highlighted" class="bg-color-grayLight1">
      <div class="container">
        <div class="row">
          <div class="highlighted-blog-single col-xs-12">
            <div class="fade-in text-center vertical-center">
              <h2 class="blog-single-title text-color-theme">{{ 'title' }}</h2>
            </div>
            <ul class="blog-post-info list-inline">
              <li>Alice Doe on 16 May</li>
              <li><a href="#">46.2K Plays / 711 Likes / 12 Comments</a></li>
              <li>1 Year ago</li>
            </ul>
          </div> <!-- /highlighted-image-blog -->

        </div> <!-- /row -->
      </div> <!-- /container -->      
</div> <!-- /highlighted -->

  <div id="blog-single" class="content">
      <div class="container">
        <div class="row">

          <div class="main-content col-xs-12 col-md-8 col-md-offset-2">
            <div class="region">
                  <br>
                  <div class="blog-single-post-content">
                      {{ Datatable::table()
                        ->addColumn('id','category','slug')       // these are the column headings to be shown
                        ->setUrl(route('api.categories'))   // this is the route where data will be retrieved
                        ->render() }}
                  </div> <!-- /blog-single-post-content -->

                  <div class="theme-comments">
                        
                    <h4 class="theme-comments-title">Comments</h4>
                    
                    <form class="form-horizontal" method="post" role="form">
                    
                      
                   
                      
                      <div class="form-group">
                        <div class="col-xs-12">
                          <textarea class="form-control" rows="8" id="comment-comment" name="comment-comment" placeholder="Comment"></textarea>
                        </div> <!-- /col-xs-12 -->
                      </div> <!-- /form-group -->
                      
                      <div class="form-group text-center">
                        <div class="col-xs-12">
                          <input type="submit" class="btn btn-primary btn-sm btn-block margin-top-20" id="submit" name="submit" value="submit comment" />
                        </div> <!-- /col-xs-12 -->
                      </div> <!-- /form-group -->
                    </form>
                    
                    <div class="theme-comment">
                      <div class="row">
                        <div class="theme-comment-picture col-sm-2 hidden-xs">
                          <img src="img/people/user1.jpg" class="img-responsive" alt="User 1" title="User 1" />
                        </div> <!-- /theme-comment-info -->
                        
                        <div class="theme-comment-message col-sm-10">
                          <h5 class="theme-comment-subject">Lorem Ipsum</h5>
                          <p class="theme-comment-info"><small>John Doe on Fri, 05/17/2014 - 10:19</small></p>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim felis, mollis a lacinia laoreet, rutrum at velit. Fusce quis neque nisl. Proin faucibus leo fermentum venenatis pharetra. Aenean placerat scelerisque justo, ac ultrices neque interdum eu. Praesent et lobortis nunc.</p>
                          <p>In ac vulputate nisi. Aliquam aliquam viverra magna id sollicitudin.</p>
                          <p><small><a href="#">reply</a></small></p>
                        </div> <!-- /theme-comment-message -->
                      </div> <!-- /row -->
                    </div> <!-- /theme-comment -->
                    
                    <div class="theme-comment">
                      <div class="row">
                        <div class="theme-comment-picture col-sm-2 hidden-xs">
                          <img src="img/people/user2.jpg" class="img-responsive" alt="User 2" title="User 2" />
                        </div> <!-- /theme-comment-info -->
                        
                        <div class="theme-comment-message col-sm-10">
                          <h5 class="theme-comment-subject">Proin aliquam</h5>
                          <p class="theme-comment-info"><small>Jane Doe on Thu, 05/16/2014 - 12:44</small></p>
                          <p>Fusce et pharetra massa. Proin aliquam eros porttitor nulla dictum sollicitudin. Suspendisse potenti. Etiam ac odio nec est cursus luctus et id turpis.</p>
                          <p>Duis varius nunc id semper tincidunt. Aenean sit amet velit eleifend, rhoncus metus a, feugiat enim. Sed vestibulum leo quis lectus semper, eget pulvinar ligula adipiscing.</p>
                          <p><small><a href="#">reply</a></small></p>
                        </div> <!-- /theme-comment-message -->
                      </div> <!-- /row -->
                    </div> <!-- /theme-comment -->

                  </div> <!-- /theme-comments -->

                </div> <!-- /blog-post -->
              </div> <!-- /blog-content-block -->

            </div> <!-- /region -->
          </div> <!-- /main-content -->

        </div> <!-- /row -->
      </div> <!-- /container -->
    </div> <!-- /content -->